version: '3.8'

services:
  db:
    image: postgres:15
    container_name: finance-app-db
    restart: always
    environment:
      POSTGRES_DB: finance-app-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: fadbp01
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
